### ISSUE TITLE
crash on start in MacOS Sierra

### ISSUE THREAD

**Issue by drummwill** [alexkay/spek#114]

**Comment by es0phagus** [comment]
Yep, doesn't load on Sierra for some reason.

**Comment by Alimog92** [comment]
Came here to write this too. Downloaded OS Sierra, and when I click to open the application, I get a 'The application "Spek" can't be opened'. 

Crash report:

Process:               Spek [7393]
Path:                  /Applications/Spek.app/Contents/MacOS/Spek
Identifier:            org.spek-project
Version:               ???
Code Type:             X86 (Native)
Parent Process:        ??? [1]
Responsible:           Spek [7393]
User ID:               501

Date/Time:             2016-09-26 13:57:12.914 +0100
OS Version:            Mac OS X 10.12 (16A323)
Report Version:        12
Anonymous UUID:        012857A2-C2FE-02A2-8673-57C7774077F9

Sleep/Wake UUID:       3CFAD9E0-8E61-4458-92B8-95570F1EB72D

Time Awake Since Boot: 95000 seconds
Time Since Wake:       4500 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000241499f5
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

Backtrace not available

Unknown thread crashed with X86 Thread State (32-bit):
  eax: 0x248b8b5b  ebx: 0xbffffd20  ecx: 0x241499f5  edx: 0x00000001
  edi: 0xbffffd50  esi: 0x00000000  ebp: 0xbffffce8  esp: 0xbffffca0
   ss: 0x00000023  efl: 0x00010297  eip: 0x000011bb   cs: 0x0000001b
   ds: 0x00000023   es: 0x00000023   fs: 0x00000000   gs: 0x0000000f
  cr2: 0x241499f5
  
Logical CPU:     0
Error Code:      0x00000004
Trap Number:     14


Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 52068
    thread_create: 0
    thread_set_state: 0

Model: MacBookPro12,1, BootROM MBP121.0167.B17, 2 processors, Intel Core i5, 2.9 GHz, 8 GB, SMC 2.28f7
Graphics: Intel Iris Graphics 6100, Intel Iris Graphics 6100, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80CE, 0x4B3445364533303445452D45474346000000
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80CE, 0x4B3445364533303445452D45474346000000
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.21.171.10.1a16)
Bluetooth: Version 5.0.0f18, 3 services, 17 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512G, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by pisymbol** [comment]
Same.

**Comment by alexkay** [comment]
UPX (the tool Spek uses to compact binaries) is broken on Sierra, they are working on it: https://github.com/upx/upx/issues/4

**Comment by alexkay** [comment]
There's an earlier issue #107, closing as a dupe.
