### ISSUE TITLE
spek not reading files

### ISSUE THREAD

**Issue by 19141** [alexkay/spek#152]
sometimes spek doesn't read audio files, any reason why? either i get the message no audio channels or unknown duration. i can play files and they do work

![fa6b03b554f73428823a6229d64ed8e6](https://user-images.githubusercontent.com/32970570/31845007-a0d6ce46-b5ca-11e7-8860-4adfe73ae96c.png)

![699621fe2ae479b19d94f5ae20e0ef4e](https://user-images.githubusercontent.com/32970570/31845009-a550a280-b5ca-11e7-9a7a-eb1a7d955332.png)

**Comment by withmorten** [comment]
Is it possible these mp3 files have a cover? The Spek uses horribly outdated ffmpeg libraries, all these issues with mp3 files should be fixed in newer versions.

If you're on Windows, I recently made a newer build of Spek with later ffmpeg libraries, can you see if this problem persists with this version?

https://github.com/withmorten/spek/releases

**Comment by alexkay** [comment]
This should work in 0.8.5. If you are on Windows, could you check the beta version? https://github.com/alexkay/spek/releases/tag/v0.8.5
