### ISSUE TITLE
isn't working on High Sierra

### ISSUE THREAD

**Issue by matt98pe** [alexkay/spek#155]
i can't open the app on High Sierra. anyone has any idea of what's happening?

**Comment by dastefster** [comment]
which version of Spek do you have installed?
I'm running the latest version of High Sierra (10.13.1) and haven't had any issues launching or using Spek.

**Comment by psobko** [comment]
0.8.2 isn't working for me either

`Time Awake Since Boot: 95000 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000cec933b
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

Backtrace not available

Unknown thread crashed with X86 Thread State (32-bit):
  eax: 0x0008950c  ebx: 0xbffffc54  ecx: 0x0cec933b  edx: 0x00000001
  edi: 0xbffffc8c  esi: 0x00001000  ebp: 0xbffffc18  esp: 0xbffffbd0
   ss: 0x00000023  efl: 0x00010297  eip: 0x000013e3   cs: 0x0000001b
   ds: 0x00000023   es: 0x00000023   fs: 0x00000000   gs: 0x0000000f
  cr2: 0x0cec933b
  
Logical CPU:     0
Error Code:      0x00000004
Trap Number:     14


Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 68353
    thread_create: 0
    thread_set_state: 0

Model: MacBookPro11,5, BootROM MBP114.0177.B00, 4 processors, Intel Core i7, 2.5 GHz, 16 GB, SMC 2.30f2
Graphics: AMD Radeon R9 M370X, AMD Radeon R9 M370X, PCIe, 2 GB
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.77.37.0.1a1)
Bluetooth: Version 6.0.0f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: USB Ethernet, Ethernet, en4
Serial ATA Device: APPLE SSD SM0512G, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Bluetooth USB Host Controller
USB Device: AX88772B
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1
`

**Comment by arnaubt** [comment]
Same here on High Sierra 10.13.2

**Comment by MaffooBristol** [comment]
I'm on normal Sierra and I get this issue too, same thing. Segmentation fault 11

**Comment by cuhieptinhte** [comment]
HEY GUYS, I DONT KNOW WHY BUT I FOUND A TEMPORARILY SOLUTION:

I click with both fingers, then chose to open the file I attached in this post. I work with Sierra. 
(How ever, I tried to copy this file to Application to replace the file in there but still error if open as usual) --> solution:

1. Copy this file to your Mac, to any folder, i.e. "setup1"
2. Each time you need to open an mp3 with this, click with both finger >>> chose "Open with" >>> "Other" >>>>>> then browse the file in the "setup1" .
it works!
[Spek.app.zip](https://github.com/alexkay/spek/files/1608831/Spek.app.zip)
 
![screen shot 2018-01-06 at 8 51 14 pm](https://user-images.githubusercontent.com/35169652/34640345-7f9af7f2-f323-11e7-9d21-5e494f923fdd.png)

**Comment by withmorten** [comment]
Can you all check if this build also causes problems?

https://github.com/withmorten/spek-alternative/releases/tag/0.8.2.3

Has no UPX compression and includes that alignment patch that caused Spek to segfault most of the time when opening files.

**Comment by thomaskyhn** [comment]
0.8.2.3 works here, so far.

**Comment by withmorten** [comment]
Glad to hear that! I only had a macOS 10.12 vm to test it, so I wasn't sure how it would fare on newer macOS versions.

**Comment by zADANLAVEY** [comment]
@withmorten Is there a reason for the app to try to connect to your website? (https://morten.with.de/).
v0.8.2.3 is working on Sierra but that behavior is suspicious...

**Comment by withmorten** [comment]
Yes, that's how it checks if there's an update, if you check the source it opens this file every 7 days: https://morten.with.de/spek

That's how the original spek checks it, too, btw, except that one opens http://spek.cc/version.

https://github.com/alexkay/spek/blob/master/src/spek-window.cc#L365

https://github.com/withmorten/spek-alternative/blob/alternative/src/spek-window.cc#L366

**Comment by alexkay** [comment]
I added an updated beta package of macOS for the latest release. Try it out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
