### ISSUE TITLE
please make a new release

### ISSUE THREAD

**Issue by 0-wiz-0** [alexkay/spek#157]
For the packagers, so they can switch this to a newer ffmpeg version.
Thank you.

**Comment by Sonicpromo** [comment]
Yes please

**Comment by livingsilver94** [comment]
Yes please!

**Comment by reallyuniquename** [comment]
Is there an official release for Windows built from latest sources? I see there were [tons of fixes and features](https://github.com/alexkay/spek/compare/v0.8.3...master) added since v0.8.3.

Here in issues users still request things that were already implemented because latest build is not up to date.

**Comment by alexkay** [comment]
0.8.5 is out, supporting ffmpeg 5.1. It includes a beta Windows installer, macOS installer is coming soon: https://github.com/alexkay/spek/releases/tag/v0.8.5
