### ISSUE TITLE
Spek crashes on opening in Mac Mojave 10.14

### ISSUE THREAD

**Issue by emmanuelrcruz** [alexkay/spek#168]
Spek crashes on opening in Mac Mojave 10.14

**Comment by withmorten** [comment]
Can you give this a try?

https://github.com/withmorten/spek-alternative/releases

**Comment by emmanuelrcruz** [comment]
Thanks, this alternative works.

**Comment by gdob** [comment]
@withmorten Thank you million times!

**Comment by chuck12138** [comment]
@withmorten Really helped! Thanks!

**Comment by george990** [comment]
Hi, i have followed the new download link you posted above and it works and opens so thank you!

 I have found an issue with the results spek is giving. I ran the same song though my mac and on a pc. The pc version is showing a completely different graph to my mac. The song looks a lot better quality on the PC scan.

Is this a known issue between mac and pc for this software? also is there any way to fix it?
Thanks

**Comment by withmorten** [comment]
The standard resolution is different for mac and PC because of the way calculcates the "render" window minus the toolbar and something, if I remember correctly. Standard resolution should be 640x480 for both, try saving the image, check the resolution and change it either on mac or PC so the resolution of the resulting image is the same. Images generated on mac should be "higher".

I have a more recent build than the released build here in the comments: https://github.com/withmorten/spek-alternative/commit/084ce47e340b9a799fc62099cb91a7fb605203cc

It has a preferences option to change the startup resolution in ~/.config/spek/preferences. In "general", change width=640 and height=480.

**Comment by Kwadz** [comment]
@withmorten, good job! Would you be able to make a pull request with your update?

**Comment by mattpopovich** [comment]
See #160. I recommend to close this duplicate issue.

**Comment by dikafe** [comment]
Thank you!

**Comment by alexkay** [comment]
I added an updated beta package of macOS for the latest release. Try it out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5
