### ISSUE TITLE
Distorted Images on Ultrawide Monitor

### ISSUE THREAD

**Issue by otpatientot** [alexkay/spek#219]
Hello, I love the program but there is an issue when using it on an ultrawide monitor. The display of the graphs gets cut off on the top and sides a bit. If there was a way to fix this, that would be fantastic. Thanks. 
![Bunnymen Crododiles 01-01 Going Up flac](https://user-images.githubusercontent.com/100525882/155888370-873811f1-bc26-4c27-aa0f-9262428bc549.png)

**Comment by renekuhs** [comment]
This is due to Windows DPI scaling.
As a workaround, open the properties of spek.exe (or a shortcut to it) and go to the Compatibility tab. Click on "Change high DPI settings" and select the "Override high DPI scaling behaviour" checkbox and select the "System" option in the dropdown below it.

This has the drawback of not rendering the window at native resolution though, so the rendered spectogram image will be slightly blurry.

**Comment by alexkay** [comment]
HiDPI support is added in beta packages for Windows for the latest release. Try them out and let me know if anything is off: https://github.com/alexkay/spek/releases/tag/v0.8.5

**Comment by renekuhs** [comment]
Works perfectly for me, thanks Alex!
